//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.CompanyAccount = new HashSet<CompanyAccount>();
        }
    
        public int AccountTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<long> DefaultMaxTransactions { get; set; }
        public Nullable<decimal> DefaultSetupFee { get; set; }
        public Nullable<decimal> DefaultLicenseFee { get; set; }
        public Nullable<decimal> DefaultTFRate { get; set; }
        public Nullable<decimal> DefaultDIDRate { get; set; }
        public Nullable<decimal> DefaultTerminationRate { get; set; }
        public Nullable<int> DefaultIVRBillingIncrement { get; set; }
        public Nullable<decimal> DefaultSMSMORate { get; set; }
        public Nullable<decimal> DefaultSMSMTRate { get; set; }
        public Nullable<int> DefaultPSMSPayoutTypeID { get; set; }
        public Nullable<double> DefaultPSMSPayoutValue { get; set; }
        public Nullable<int> DefaultSoftwareLicenseTypeID { get; set; }
    
        public virtual PSMSPayoutType PSMSPayoutType { get; set; }
        public virtual SoftwareLicenseType SoftwareLicenseType { get; set; }
        public virtual ICollection<CompanyAccount> CompanyAccount { get; set; }
    }
}
