//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastSMSQueue
    {
        public BroadcastSMSQueue()
        {
            this.BroadcastSMSFilter = new HashSet<BroadcastSMSFilter>();
        }
    
        public long BroadcastSMSQueueID { get; set; }
        public long CompanyID { get; set; }
        public string CampaignID { get; set; }
        public string MessageFlowID { get; set; }
        public long TotalRows { get; set; }
        public string ShortCodeProvider { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public long ShortCodeInfoID { get; set; }
        public string MessageText { get; set; }
        public string BroadcastSMSBatchID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> BroadcastSMSRecordsCreated { get; set; }
        public Nullable<bool> IsSmartSMS { get; set; }
        public Nullable<bool> IsAPI { get; set; }
        public Nullable<bool> IsNationalBroadcast { get; set; }
        public Nullable<long> BroadcastTypeID { get; set; }
        public Nullable<System.DateTime> BroadcastSendDate { get; set; }
        public Nullable<bool> IsBroadcastSent { get; set; }
        public Nullable<bool> IsBroadcastCanceled { get; set; }
        public string SmartSMSCouponName { get; set; }
    
        public virtual ICollection<BroadcastSMSFilter> BroadcastSMSFilter { get; set; }
    }
}
