//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastSMSMessagetextArchive
    {
        public long BroadcastSMSMessagetextArchiveID { get; set; }
        public long CompanyID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
