//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastSMSSubscriptions
    {
        public int BroadcastSMSBatchID { get; set; }
        public long MessageFlowID { get; set; }
        public Nullable<long> BroadcastSMSQueueID { get; set; }
        public Nullable<long> CampaignID { get; set; }
    }
}
