//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastSMSUniversalSendPageExecuteLog
    {
        public int BroadcastSMSUniversalSendPageID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CampaignID { get; set; }
        public string MessageFlowID { get; set; }
        public string ShortCodeProvider { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<long> ShortCodeInfoID { get; set; }
        public string MessageText { get; set; }
        public string BroadcastSMSBatchID { get; set; }
        public string BroadCastSMSQueueID { get; set; }
        public string ContactsSQL { get; set; }
    }
}
