//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignOld
    {
        public long CampaignID { get; set; }
        public long CompanyID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CampaignTypeID { get; set; }
        public bool UseMXCarrierLookup { get; set; }
        public bool UseNetNumberLookup { get; set; }
        public bool AMD { get; set; }
        public bool LeaveVMail { get; set; }
        public Nullable<bool> SelectedAll { get; set; }
        public string TwitterUsername { get; set; }
        public string TwitterPassword { get; set; }
        public string FBAuthCode { get; set; }
        public string TwitterToken { get; set; }
        public string TwitterTokenSecret { get; set; }
        public Nullable<long> FBFanPageID { get; set; }
        public Nullable<bool> FBUseGlobal { get; set; }
        public Nullable<bool> TwitterUseGlobal { get; set; }
        public string MaxInteractionAutoResponse { get; set; }
        public string InactiveCampaignMessageText { get; set; }
        public Nullable<bool> AlwaysActive { get; set; }
        public Nullable<bool> IsCampaignHidden { get; set; }
    }
}
