//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignAudio
    {
        public long CampaignAudioID { get; set; }
        public long CampaignID { get; set; }
        public string MobileCarrierPromptURL { get; set; }
        public string UnsupportedCarrierMessageURL { get; set; }
        public string ErrorMessageURL { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
