//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public Carrier()
        {
            this.MessageFlowCarrier = new HashSet<MessageFlowCarrier>();
            this.SCKSupportedCarrier = new HashSet<SCKSupportedCarrier>();
            this.ServiceID = new HashSet<ServiceID>();
            this.SupportedCarrier = new HashSet<SupportedCarrier>();
        }
    
        public long CarrierID { get; set; }
        public string Description { get; set; }
        public string MXTelecomID { get; set; }
        public Nullable<long> mBloxID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool ShowInUI { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string NetNumberID { get; set; }
        public Nullable<long> SybaseID { get; set; }
        public Nullable<long> MotricityID { get; set; }
        public Nullable<long> FourInfoID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<MessageFlowCarrier> MessageFlowCarrier { get; set; }
        public virtual ICollection<SCKSupportedCarrier> SCKSupportedCarrier { get; set; }
        public virtual ICollection<ServiceID> ServiceID { get; set; }
        public virtual ICollection<SupportedCarrier> SupportedCarrier { get; set; }
    }
}
