//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTransaction
    {
        public long CCTransactionID { get; set; }
        public Nullable<long> CCNumber { get; set; }
        public string CCAddress { get; set; }
        public string CCAddress2 { get; set; }
        public string CCCity { get; set; }
        public string CCState { get; set; }
        public string CCZip { get; set; }
        public Nullable<long> CCExpiration { get; set; }
        public Nullable<int> CCCVV { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CCTransactionNumber { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<long> PaymentGatewayID { get; set; }
        public bool MonthlyBill { get; set; }
    
        public virtual PaymentGateway PaymentGateway { get; set; }
    }
}
