//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDRLogTEST
    {
        public long CDRLogTESTID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public long CDRID { get; set; }
        public int CDRLogTypeID { get; set; }
        public Nullable<long> TargetID { get; set; }
        public Nullable<long> IVRTreeID { get; set; }
    }
}
