//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Campaign = new HashSet<Campaign>();
            this.CompanyAccount = new HashSet<CompanyAccount>();
            this.CompanyIVRRate = new HashSet<CompanyIVRRate>();
            this.CompanyMessageRate = new HashSet<CompanyMessageRate>();
            this.ShortCodeInfo = new HashSet<ShortCodeInfo>();
        }
    
        public long CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public long Phone { get; set; }
        public Nullable<long> Fax { get; set; }
        public string AudioURL { get; set; }
        public bool ACH { get; set; }
        public bool CC { get; set; }
        public bool Balance { get; set; }
        public string Email { get; set; }
        public string BillingContact { get; set; }
        public string BillingAddress { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public Nullable<long> BillingPhone { get; set; }
        public string BillingCountry { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
        public string LogoURL { get; set; }
        public Nullable<bool> ExportBroadcastBatchIdList { get; set; }
        public Nullable<bool> CanViewFullPhoneNumber { get; set; }
        public Nullable<int> SREntityID { get; set; }
        public Nullable<long> CRMID { get; set; }
        public string CompanyVerticle { get; set; }
        public Nullable<bool> isDemo { get; set; }
        public Nullable<bool> isSuspended { get; set; }
        public Nullable<bool> CanViewCustomMessageFlows { get; set; }
        public Nullable<bool> CanViewTargets { get; set; }
        public Nullable<bool> LikeDislikeEnabled { get; set; }
        public Nullable<int> DelayedOptin { get; set; }
        public Nullable<int> CountdownTime { get; set; }
        public Nullable<bool> EnableDelayedOptin { get; set; }
        public Nullable<bool> EnableCountdowntime { get; set; }
    
        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual ICollection<CompanyAccount> CompanyAccount { get; set; }
        public virtual ICollection<CompanyIVRRate> CompanyIVRRate { get; set; }
        public virtual ICollection<CompanyMessageRate> CompanyMessageRate { get; set; }
        public virtual ICollection<ShortCodeInfo> ShortCodeInfo { get; set; }
    }
}
