//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAccount
    {
        public long CompanyAccountID { get; set; }
        public long CompanyID { get; set; }
        public int AccountTypeID { get; set; }
        public Nullable<long> MaxTransactions { get; set; }
        public Nullable<decimal> SetupFee { get; set; }
        public Nullable<decimal> LicenseFee { get; set; }
        public Nullable<decimal> TFRate { get; set; }
        public Nullable<decimal> DIDRate { get; set; }
        public Nullable<decimal> TerminationRate { get; set; }
        public Nullable<int> IVRBillingIncrement { get; set; }
        public Nullable<decimal> SMSMORate { get; set; }
        public Nullable<decimal> SMSMTRate { get; set; }
        public Nullable<int> PSMSPayoutTypeID { get; set; }
        public Nullable<double> PSMSPayoutValue { get; set; }
        public Nullable<int> SoftwareLicenseTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Company Company { get; set; }
        public virtual PSMSPayoutType PSMSPayoutType { get; set; }
        public virtual SoftwareLicenseType SoftwareLicenseType { get; set; }
    }
}
