//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMarket
    {
        public long CompanyMarketID { get; set; }
        public long CompanyID { get; set; }
        public string MarketName { get; set; }
        public string MarketDescription { get; set; }
        public Nullable<long> SmartReceiptEntityID { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
