//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyIVRRate
    {
        public long CompanyIVRRateID { get; set; }
        public long CompanyID { get; set; }
        public int CDRTypeID { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CDRType CDRType { get; set; }
        public virtual Company Company { get; set; }
    }
}
