//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetailsWithPagingExecuteLog
    {
        public int ContactDetailsWithPagingID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CampaignID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SortBy { get; set; }
        public string SortType { get; set; }
        public string TextQuery { get; set; }
        public string MessageFlowID { get; set; }
        public string DID { get; set; }
        public string CarrierID { get; set; }
        public Nullable<bool> NoZip { get; set; }
        public Nullable<bool> YesZip { get; set; }
        public Nullable<int> Zip { get; set; }
        public string State { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<bool> CampaignBased { get; set; }
        public string Contacts { get; set; }
    }
}
