//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTickerMessage
    {
        public int CustomTickerMessageId { get; set; }
        public int GraphicID { get; set; }
        public string BucketName { get; set; }
        public string Channel { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> TimeReceived { get; set; }
        public string MessageText { get; set; }
        public string Email { get; set; }
        public Nullable<int> StatusType { get; set; }
    
        public virtual Graphic Graphic { get; set; }
    }
}
