//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_Category
    {
        public DA_Category()
        {
            this.DA_DirectoryEntry = new HashSet<DA_DirectoryEntry>();
        }
    
        public int DA_CategoryID { get; set; }
        public long CampaignID { get; set; }
        public string Description { get; set; }
        public string OriginalCategoryID { get; set; }
        public bool SuperCategory { get; set; }
    
        public virtual ICollection<DA_DirectoryEntry> DA_DirectoryEntry { get; set; }
    }
}
