//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_DirectoryEntry
    {
        public DA_DirectoryEntry()
        {
            this.DA_EntryAlias = new HashSet<DA_EntryAlias>();
            this.DA_Category = new HashSet<DA_Category>();
        }
    
        public long DA_DirectoryEntryID { get; set; }
        public long CampaignID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<long> Phone { get; set; }
        public string OriginalCategory1 { get; set; }
        public string OriginalCategory2 { get; set; }
        public string OriginalCategory3 { get; set; }
        public string OriginalCategory4 { get; set; }
        public string OriginalCategory5 { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> ShowInCategory { get; set; }
        public string CustomAudioURL { get; set; }
        public Nullable<bool> DirectConnect { get; set; }
    
        public virtual ICollection<DA_EntryAlias> DA_EntryAlias { get; set; }
        public virtual ICollection<DA_Category> DA_Category { get; set; }
    }
}
