//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_EntryAlias
    {
        public long DA_DirectoryEntryID { get; set; }
        public string Alias { get; set; }
    
        public virtual DA_DirectoryEntry DA_DirectoryEntry { get; set; }
    }
}
