//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DID
    {
        public DID()
        {
            this.OutboundCallSchedule = new HashSet<OutboundCallSchedule>();
            this.OutboundCallSubscriptionList = new HashSet<OutboundCallSubscriptionList>();
        }
    
        public long DID1 { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public Nullable<long> IVRTreeID { get; set; }
        public bool TollFree { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual IVRTree IVRTree { get; set; }
        public virtual ICollection<OutboundCallSchedule> OutboundCallSchedule { get; set; }
        public virtual ICollection<OutboundCallSubscriptionList> OutboundCallSubscriptionList { get; set; }
    }
}
