//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphic
    {
        public Graphic()
        {
            this.CustomTickerMessage = new HashSet<CustomTickerMessage>();
        }
    
        public int GraphicId { get; set; }
        public string Title { get; set; }
        public int GraphicType { get; set; }
        public string Email { get; set; }
        public string TickerURL { get; set; }
        public Nullable<int> StatusType { get; set; }
        public Nullable<int> GraphicTemplateId { get; set; }
        public Nullable<int> GraphicBackgroundID { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public string BackgroundColor { get; set; }
    
        public virtual ICollection<CustomTickerMessage> CustomTickerMessage { get; set; }
        public virtual GraphicBackground GraphicBackground { get; set; }
        public virtual GraphicTemplate GraphicTemplate { get; set; }
    }
}
