//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicTemplate
    {
        public GraphicTemplate()
        {
            this.Graphic = new HashSet<Graphic>();
            this.GraphicBackground = new HashSet<GraphicBackground>();
            this.GraphicTemplateParam = new HashSet<GraphicTemplateParam>();
        }
    
        public int GraphicTemplateId { get; set; }
        public int GraphicFormatId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Title { get; set; }
        public string LayoutUrl { get; set; }
        public string LayoutXml { get; set; }
        public string BackgroundColour { get; set; }
        public Nullable<int> ShowId { get; set; }
    
        public virtual ICollection<Graphic> Graphic { get; set; }
        public virtual ICollection<GraphicBackground> GraphicBackground { get; set; }
        public virtual GraphicFormat GraphicFormat { get; set; }
        public virtual ICollection<GraphicTemplateParam> GraphicTemplateParam { get; set; }
    }
}
