//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicExtraElement
    {
        public int GraphicExtraElementId { get; set; }
        public int GraphicId { get; set; }
        public string ElementKey { get; set; }
        public string Value { get; set; }
    }
}
