//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicFormat
    {
        public GraphicFormat()
        {
            this.GraphicTemplate = new HashSet<GraphicTemplate>();
            this.GraphicTemplateParamDefinition = new HashSet<GraphicTemplateParamDefinition>();
        }
    
        public int GraphicFormatId { get; set; }
        public string Title { get; set; }
        public string EditorUrl { get; set; }
        public string SwfUrl { get; set; }
        public string SmsEditorUrl { get; set; }
        public string AdvancedEditorUrl { get; set; }
        public Nullable<int> GraphicType { get; set; }
    
        public virtual ICollection<GraphicTemplate> GraphicTemplate { get; set; }
        public virtual ICollection<GraphicTemplateParamDefinition> GraphicTemplateParamDefinition { get; set; }
    }
}
