//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicTemplateParamDefinition
    {
        public int GraphicFormatId { get; set; }
        public string GraphicTemplateParamKey { get; set; }
        public string Title { get; set; }
        public string ParamValueFormat { get; set; }
        public Nullable<bool> Required { get; set; }
        public bool Editable { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual GraphicFormat GraphicFormat { get; set; }
    }
}
