//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVRTreeInput
    {
        public long IVRTreeInputID { get; set; }
        public long IVRTreeID { get; set; }
        public string IVRInputValue { get; set; }
        public int IVRInputValueTypeID { get; set; }
        public bool PoundTerminated { get; set; }
        public long IVRTreeDestinationID { get; set; }
        public string VariableName { get; set; }
    
        public virtual IVRInputValueType IVRInputValueType { get; set; }
        public virtual IVRTree IVRTree { get; set; }
        public virtual IVRTree IVRTree1 { get; set; }
    }
}
