//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVRTreeDynamicAudio
    {
        public int IVRTreeDynamicAudioID { get; set; }
        public long CampaignID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> CallerID { get; set; }
        public long DID { get; set; }
        public int Sequence { get; set; }
        public string AudioURL { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
