//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox
    {
        public MailBox()
        {
            this.VoiceMail = new HashSet<VoiceMail>();
        }
    
        public long MailBoxID { get; set; }
        public long CampaignID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> TargetID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public Nullable<int> PIN { get; set; }
        public string AudioPath { get; set; }
        public string VoicemailGreetingURL { get; set; }
        public string PostVoicemailMenuURL { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Target Target { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<VoiceMail> VoiceMail { get; set; }
    }
}
