//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxReplies
    {
        public long MaxRepliesID { get; set; }
        public long CampaignID { get; set; }
        public int NumberOfReplies { get; set; }
        public int TimePeriodID { get; set; }
        public Nullable<long> IVRTreeDestinationID { get; set; }
        public Nullable<long> MessagingTargetID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual IVRTree IVRTree { get; set; }
        public virtual Target Target { get; set; }
        public virtual TimePeriod TimePeriod { get; set; }
    }
}
