//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public Messages()
        {
            this.MessageDetails = new HashSet<MessageDetails>();
        }
    
        public long Id { get; set; }
        public string Message { get; set; }
        public long UserId { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool IsRandom { get; set; }
        public string ShortCode { get; set; }
        public Nullable<long> ShortCodeInfoId { get; set; }
    
        public virtual ICollection<MessageDetails> MessageDetails { get; set; }
        public virtual User User { get; set; }
    }
}
