//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageFlowSchedule
    {
        public long MessageFlowScheduleID { get; set; }
        public Nullable<System.DateTime> NextScheduledTime { get; set; }
        public string Schedule { get; set; }
        public long MessageFlowID { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
    
        public virtual MessageFlow MessageFlow { get; set; }
    }
}
