//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageFlowType
    {
        public MessageFlowType()
        {
            this.MessageFlow = new HashSet<MessageFlow>();
        }
    
        public long MessageFlowTypeID { get; set; }
        public string MessageFlowTypeText { get; set; }
    
        public virtual ICollection<MessageFlow> MessageFlow { get; set; }
    }
}
