//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageDelayed
    {
        public long MessageDelayedID { get; set; }
        public long MessageFlowID { get; set; }
        public Nullable<int> DelayMinutes { get; set; }
        public Nullable<System.DateTime> DelayTime { get; set; }
        public string MessageText { get; set; }
    }
}
