//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageDetails
    {
        public long Id { get; set; }
        public long MessageId { get; set; }
        public string Phone { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual User User { get; set; }
    }
}
