//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileInfo
    {
        public long MobileInfoID { get; set; }
        public long MobileModelID { get; set; }
        public string UserAgent { get; set; }
        public Nullable<int> PreferredMarkupTypeID { get; set; }
        public Nullable<int> ResolutionWidth { get; set; }
        public Nullable<int> ResolutionHeight { get; set; }
        public Nullable<int> MaxImageWidth { get; set; }
        public Nullable<int> MaxImageHeight { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual MobileModel MobileModel { get; set; }
    }
}
