//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPTTCode
    {
        public int mPTTCodeID { get; set; }
        public string StatusDesc { get; set; }
        public string ReasonDescription { get; set; }
        public string Status { get; set; }
        public string Explanation { get; set; }
    }
}
