//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundEventScheduler
    {
        public long OutboundEventSchedulerID { get; set; }
        public long UserID { get; set; }
        public System.DateTime ApproxWindowStart { get; set; }
        public Nullable<System.DateTime> ApproxWindowEnd { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public bool EventQueued { get; set; }
        public bool Completed { get; set; }
        public int OutboundEventTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual OutboundEventType OutboundEventType { get; set; }
        public virtual User User { get; set; }
    }
}
