//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public PaymentGateway()
        {
            this.CCTransaction = new HashSet<CCTransaction>();
            this.Target = new HashSet<Target>();
        }
    
        public long PaymentGatewayID { get; set; }
        public int GatewayID { get; set; }
        public int GatewayTypeID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CCTransaction> CCTransaction { get; set; }
        public virtual Gateway Gateway { get; set; }
        public virtual GatewayType GatewayType { get; set; }
        public virtual ICollection<Target> Target { get; set; }
    }
}
