//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDSHour
    {
        public long PDSHourID { get; set; }
        public long PredictiveDialerScheduleID { get; set; }
        public int Hour { get; set; }
        public int MaxTransfers { get; set; }
        public bool EasternTime { get; set; }
        public bool CentralTime { get; set; }
        public bool MountainTime { get; set; }
        public bool PacificTime { get; set; }
    
        public virtual PredictiveDialerSchedule PredictiveDialerSchedule { get; set; }
    }
}
