//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictiveDialerBadNumbers
    {
        public long BadID { get; set; }
        public long CompanyID { get; set; }
        public long PredictiveDialerScheduleID { get; set; }
        public string Phone { get; set; }
    }
}
