//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictiveDialerSchedule
    {
        public PredictiveDialerSchedule()
        {
            this.PDSHour = new HashSet<PDSHour>();
        }
    
        public long PredictiveDialerScheduleID { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public long CampaignID { get; set; }
        public Nullable<int> EstimatedCallsPerTransfer { get; set; }
        public Nullable<double> iGain { get; set; }
        public Nullable<double> pGain { get; set; }
        public Nullable<int> MaxCallsPerIteration { get; set; }
        public Nullable<long> CallerID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<PDSHour> PDSHour { get; set; }
    }
}
