//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferAFriendOffer
    {
        public long ReferAFriendOfferId { get; set; }
        public long ShortCodeKeywordId { get; set; }
        public long CampaignId { get; set; }
        public Nullable<long> MessageFlowId { get; set; }
        public bool Active { get; set; }
        public string OfferMessageText { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DeactivateDate { get; set; }
        public string KeyWord { get; set; }
        public string AutoResponseText { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual MessageFlow MessageFlow { get; set; }
        public virtual ShortCodeKeyword ShortCodeKeyword { get; set; }
    }
}
