//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderInfo
    {
        public long ReminderID { get; set; }
        public long UserID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> CompanyPhone { get; set; }
        public Nullable<long> MessageFlowID { get; set; }
        public Nullable<long> TargetID { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public string TimeZone { get; set; }
    }
}
