//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledReports
    {
        public long ID { get; set; }
        public string ReportName { get; set; }
        public int ReportTypeID { get; set; }
        public int TimePeriodID { get; set; }
        public string CampaignIDs { get; set; }
        public System.DateTime StartDate { get; set; }
        public int RepeatTypeID { get; set; }
        public int RepeatInterval { get; set; }
        public Nullable<bool> IsMon { get; set; }
        public Nullable<bool> IsTue { get; set; }
        public Nullable<bool> IsWed { get; set; }
        public Nullable<bool> IsThu { get; set; }
        public Nullable<bool> IsFri { get; set; }
        public Nullable<bool> IsSat { get; set; }
        public Nullable<bool> IsSun { get; set; }
        public Nullable<bool> NeverEnds { get; set; }
        public Nullable<int> EndsAfterOccurrences { get; set; }
        public Nullable<System.DateTime> EndsOn { get; set; }
        public string Recipients { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsEnded { get; set; }
    
        public virtual RepeatTypes RepeatTypes { get; set; }
        public virtual ReportTypes ReportTypes { get; set; }
        public virtual TimePeriods TimePeriods { get; set; }
        public virtual User User { get; set; }
    }
}
