//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortCodeInfo
    {
        public ShortCodeInfo()
        {
            this.ShortCodeKeyword = new HashSet<ShortCodeKeyword>();
        }
    
        public long ShortCodeInfoID { get; set; }
        public long ShortCode { get; set; }
        public int ShortCodeProviderID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public long CompanyID { get; set; }
        public string mBloxProfileID { get; set; }
        public string mBloxServerURL { get; set; }
        public bool Active { get; set; }
        public int ShortCodeTransportID { get; set; }
        public bool HighVolumeEnabled { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ShortCodeProvider ShortCodeProvider { get; set; }
        public virtual ICollection<ShortCodeKeyword> ShortCodeKeyword { get; set; }
    }
}
