//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortCodeMOOptions
    {
        public long ShortCodeMOOptionsID { get; set; }
        public long ShortCodeKeywordID { get; set; }
        public string Value { get; set; }
        public Nullable<int> MOOptionTypeID { get; set; }
        public Nullable<long> TargetID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual MOOptionType MOOptionType { get; set; }
    }
}
