//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialBroadcastQueue
    {
        public long SocialBroadcastQueueID { get; set; }
        public long CompanyID { get; set; }
        public string CampaignID { get; set; }
        public string MessageFlowID { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public string description { get; set; }
        public string MessageText { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> NextScheduledTime { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public string TwitterUsername { get; set; }
        public string TwitterToken { get; set; }
        public string TwitterTokenSecret { get; set; }
        public Nullable<long> FBFanPageID { get; set; }
        public string FBAuthCode { get; set; }
        public string FBUsername { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> Reach { get; set; }
        public string Status { get; set; }
        public string Error { get; set; }
    }
}
