//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetInteraction
    {
        public long TargetInteractionID { get; set; }
        public long CampaignID { get; set; }
        public Nullable<long> CDRID { get; set; }
        public Nullable<long> MessageTransactionID { get; set; }
        public long TargetID { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte TargetSourceID { get; set; }
    }
}
