//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetPayment
    {
        public long TargetPaymentID { get; set; }
        public long TargetID { get; set; }
        public int PaymentMethodID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Target Target { get; set; }
    }
}
