//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetOLD
    {
        public long TargetID { get; set; }
        public int ContentTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ContentURL { get; set; }
        public Nullable<long> ShortCodeKeywordID { get; set; }
        public Nullable<long> PaymentGatewayID { get; set; }
        public long CampaignID { get; set; }
        public string Description { get; set; }
        public Nullable<long> PostTargetIVRTreeDestinationID { get; set; }
        public Nullable<long> PostTargetTargetID { get; set; }
        public bool Active { get; set; }
        public string MessageText { get; set; }
        public Nullable<long> PostTargetFailureIVRTreeDestinationID { get; set; }
        public Nullable<long> PostTargetFailureTargetID { get; set; }
        public Nullable<bool> IsDBLOptIn { get; set; }
        public Nullable<int> PollAnswerID { get; set; }
    }
}
