//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_Obama_VoterLine
    {
        public int ObamaID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<long> CDRID { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<int> PollingOpen { get; set; }
        public Nullable<int> Turnout { get; set; }
        public Nullable<int> TotalVotes { get; set; }
        public Nullable<int> BarackVotes { get; set; }
        public Nullable<int> McCainVotes { get; set; }
        public Nullable<int> Precinct { get; set; }
        public Nullable<int> Legal { get; set; }
        public Nullable<int> Early { get; set; }
        public Nullable<int> Var1 { get; set; }
        public Nullable<int> Var2 { get; set; }
        public Nullable<int> Var3 { get; set; }
        public Nullable<int> Var4 { get; set; }
        public Nullable<int> Var5 { get; set; }
        public Nullable<long> CallerID { get; set; }
        public Nullable<long> CalledID { get; set; }
    }
}
