//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_CNN_Votes
    {
        public long CNNVotesID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> IVRVotes { get; set; }
        public Nullable<int> SMSVotes { get; set; }
        public Nullable<int> TotalVotes { get; set; }
        public Nullable<int> YesVote { get; set; }
        public Nullable<int> NoVote { get; set; }
        public Nullable<int> IVRPercentage { get; set; }
        public Nullable<int> SMSPercentage { get; set; }
        public Nullable<int> YesPercentage { get; set; }
        public Nullable<int> NoPercentage { get; set; }
    }
}
