//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_Obama
    {
        public int ObamaID { get; set; }
        public long CDRID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<long> precinct { get; set; }
        public Nullable<long> totalvotes { get; set; }
        public Nullable<long> barackvotes { get; set; }
        public Nullable<long> votessurvey { get; set; }
        public Nullable<long> electionbarack { get; set; }
        public Nullable<long> hillary { get; set; }
        public Nullable<long> edwards { get; set; }
        public Nullable<long> kucinich { get; set; }
        public Nullable<long> gravel { get; set; }
        public Nullable<long> other { get; set; }
        public Nullable<long> CallerID { get; set; }
        public Nullable<long> CalledID { get; set; }
        public Nullable<long> turnout { get; set; }
        public Nullable<long> uncommitted { get; set; }
        public Nullable<long> delegates { get; set; }
        public Nullable<long> BarackDelegates { get; set; }
        public Nullable<long> HillaryDelegates { get; set; }
        public Nullable<long> EdwardsDelegates { get; set; }
        public string State { get; set; }
    }
}
