//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_M_ResortNewUser
    {
        public long ID { get; set; }
        public long GeneratedAccountNumber { get; set; }
        public long UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
