//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_M_ResortMessages
    {
        public long ID { get; set; }
        public Nullable<long> AccountNumber { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Message { get; set; }
        public Nullable<long> Prize { get; set; }
    }
}
