//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_RevMsgNumberScrub
    {
        public string Firstname { get; set; }
        public string Middle { get; set; }
        public string Lastname { get; set; }
        public string Default_Address1 { get; set; }
        public string Default_Address2 { get; set; }
        public string Default_Address3 { get; set; }
        public string Default_City { get; set; }
        public string Default_State { get; set; }
        public string Default_Zip { get; set; }
        public string iContactID { get; set; }
        public string WorkPhone { get; set; }
        public string FaxPhone { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string Pager { get; set; }
        public string Other { get; set; }
        public Nullable<long> WorkPhone1 { get; set; }
        public Nullable<long> FaxPhone1 { get; set; }
        public Nullable<long> HomePhone1 { get; set; }
        public Nullable<long> CellPhone1 { get; set; }
        public Nullable<long> Page1 { get; set; }
        public Nullable<long> Other1 { get; set; }
        public string CellPhones { get; set; }
        public int PersonID { get; set; }
    }
}
