//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_QuickVote_Question
    {
        public TEMP_QuickVote_Question()
        {
            this.TEMP_QuickVote_Answer = new HashSet<TEMP_QuickVote_Answer>();
        }
    
        public long QuestionID { get; set; }
        public long C4CampaignID { get; set; }
        public long C4UserID { get; set; }
        public string Question { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string IVRGreetingURL { get; set; }
        public string IVRGoodbyeURL { get; set; }
        public string SMSReply { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<TEMP_QuickVote_Answer> TEMP_QuickVote_Answer { get; set; }
    }
}
