//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_Obama_LocalOffice
    {
        public int ObamaID { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Address_Hours { get; set; }
        public string SMS_Msg { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public Nullable<int> NextMenuID { get; set; }
    }
}
