//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_QuickVote_AnswerOption
    {
        public TEMP_QuickVote_AnswerOption()
        {
            this.TEMP_QuickVote_Answer = new HashSet<TEMP_QuickVote_Answer>();
            this.TEMP_QuickVote_Vote = new HashSet<TEMP_QuickVote_Vote>();
        }
    
        public int AnswerOptionID { get; set; }
        public string AnswerOption { get; set; }
        public int AnswerOptionGroupID { get; set; }
    
        public virtual ICollection<TEMP_QuickVote_Answer> TEMP_QuickVote_Answer { get; set; }
        public virtual ICollection<TEMP_QuickVote_Vote> TEMP_QuickVote_Vote { get; set; }
    }
}
