//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerGraphic
    {
        public TickerGraphic()
        {
            this.PromotionalMessage = new HashSet<PromotionalMessage>();
        }
    
        public int GraphicId { get; set; }
        public string SmsShoutOutId { get; set; }
        public string TickerDataUrl { get; set; }
        public bool AutoAprove { get; set; }
        public int Speed { get; set; }
        public Nullable<int> PictureWidth { get; set; }
        public Nullable<int> PictureHeight { get; set; }
        public Nullable<short> FlickerTransition { get; set; }
        public Nullable<short> FlickerDuration { get; set; }
        public Nullable<bool> FlickerStretch { get; set; }
        public Nullable<int> StartFromMessageId { get; set; }
        public Nullable<int> PromoMessageFreq { get; set; }
        public string TickerDataTimeZone { get; set; }
        public Nullable<System.DateTime> StartFromMessageDateTime { get; set; }
    
        public virtual ICollection<PromotionalMessage> PromotionalMessage { get; set; }
    }
}
