//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimePeriod
    {
        public TimePeriod()
        {
            this.MaxInteractions = new HashSet<MaxInteractions>();
            this.MaxReplies = new HashSet<MaxReplies>();
        }
    
        public int TimePeriodID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MaxInteractions> MaxInteractions { get; set; }
        public virtual ICollection<MaxReplies> MaxReplies { get; set; }
    }
}
