//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public int UserLoginHistoryID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public bool Success { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Source { get; set; }
    }
}
