//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduct
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<int> LocationRangeId { get; set; }
        public Nullable<decimal> OneTimeFee { get; set; }
        public Nullable<decimal> MonthlyRecurringFee { get; set; }
        public string Keyword { get; set; }
        public string AccountingCoachesNote { get; set; }
    
        public virtual User User { get; set; }
    }
}
