//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceMail
    {
        public long VoiceMailID { get; set; }
        public long CDRID { get; set; }
        public string AudioURL { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> UserID { get; set; }
        public bool New { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> MailBoxID { get; set; }
        public string AudioPath { get; set; }
    
        public virtual CDR CDR { get; set; }
        public virtual MailBox MailBox { get; set; }
        public virtual User User { get; set; }
    }
}
