//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingGraphic
    {
        public VotingGraphic()
        {
            this.VotingGraphicOption = new HashSet<VotingGraphicOption>();
        }
    
        public int GraphicId { get; set; }
        public string Question { get; set; }
        public string SmsPollId { get; set; }
        public string PoolDataUrl { get; set; }
        public bool OverrideVotes { get; set; }
        public Nullable<System.DateTime> VotesAfter { get; set; }
    
        public virtual ICollection<VotingGraphicOption> VotingGraphicOption { get; set; }
    }
}
