//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingGraphicOption
    {
        public int VotingGraphicOptionId { get; set; }
        public int GraphicId { get; set; }
        public string OptionKey { get; set; }
        public string OptionText { get; set; }
        public int VotesPercent { get; set; }
        public string url { get; set; }
    
        public virtual VotingGraphic VotingGraphic { get; set; }
    }
}
