//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceIdentifiedIPAddress
    {
        public long WebServiceIdentifiedIPAddressID { get; set; }
        public string IPaddress { get; set; }
        public string IdentifiedOwner { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
    }
}
