//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartsuite.bussinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipInfo
    {
        public string City { get; set; }
        public string ST { get; set; }
        public string ZIP { get; set; }
        public string A_C { get; set; }
        public string FIPS { get; set; }
        public string County { get; set; }
        public string T_Z { get; set; }
        public string DST_ { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Type { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
    }
}
